#
#
# Author:  Michael 'entropie' Trommer <mictro@gmail.com>
#

require "lib/ams"

include Rams::Database::Tables
task :a do
  pr = Product[1]
  p pr
  p pr.product_group
end


task :start do
  sh "cd app && ruby start.rb"
end

task :todofile do
  todos = User.first.todo.select{|t| t.category == "DEVEL"}
  str = "# File is Autogenerated at #{Time.now.to_s(false)}\n\n"
  todos.each do |t|
    mark = t.done == 1 ? "-" : '*'
    str << "#{mark} [#{t.created_at.to_s(false)}]\n  #{t.body}\n"
  end
  File.open("TODO", File::WRONLY|File::TRUNC|File::CREAT){|f| f.write(str)}
end


task :clean do
  require "find"
  Find.find(File.join(Dir.pwd)) do |file|
    if File.basename(file) == ".DS_Store"
      File.unlink file 
      puts file
    end
  end
end


require "dbhelper"

task :deploy => [:umigrate, :migrate, :db_fill, :todofile] do
end

task :db_fill do
  ruby "script/db_migration_devel.rb"
end

task :migrate do
  Rams::Database.migrate
end

task :umigrate do
  Rams::Database.migrate(:down)
end


task :pptables do
  Rams::Database.definitions.each do |tbl|
    puts
    puts tbl.name
    puts
    tbl.print
  end
end


=begin
Local Variables:
  mode:ruby
  fill-column:70
  indent-tabs-mode:nil
  ruby-indent-level:2
End:
=end
